// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbyuzjnujzpexriyollb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdieXV6am51anpwZXhyaXlvbGxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MTAwMzMsImV4cCI6MjA2MTE4NjAzM30.U8vqbY52Zu7cvxfTN23MMjc7wSW0_DUehi7E_3dng5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);